# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-16 02:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='ImageHasCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pins.Category')),
            ],
            options={
                'verbose_name_plural': 'pinImage has categories',
            },
        ),
        migrations.CreateModel(
            name='PinImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=10, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('image', models.FileField(upload_to='media/')),
                ('note', models.TextField(max_length=500)),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('-published',),
            },
        ),
        migrations.AddField(
            model_name='imagehascategory',
            name='pinImage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pins.PinImage'),
        ),
        migrations.AddField(
            model_name='category',
            name='images',
            field=models.ManyToManyField(through='pins.ImageHasCategory', to='pins.PinImage'),
        ),
        migrations.AlterUniqueTogether(
            name='imagehascategory',
            unique_together=set([('pinImage', 'category')]),
        ),
    ]
